### ISSUE TITLE
Tokenize.py throws IndentationError: unindent does not match any outer indentation level

### ISSUE THREAD

**Issue by schmitthub** [threatspec/threatspec#39]
Hi I'm using python 3.7.7 on Mac OSX

Here are the steps to reproduce....

```
python -m venv venv
source venv/bin/activate
pip install threatspec python-magic-bin (if i don't install python-magic-bin i get a libmagic error)
threatspec init
threatspec run

```

Here is the output 

```
Running threatspec...
Unsupported file extension .sln for mime type text/plain for file /Users/redacted/Code/threatspec-demo/Threatdiagram Sample 1.sln
Unsupported file extension .csproj for mime type text/plain for file /Users/redacted/Code/threatspec-demo/Threatdiagram Sample 1/Threatdiagram Sample 1.csproj
Unsupported file extension .cache for mime type text/plain for file /Users/redacted/Code/threatspec-demo/Threatdiagram Sample 1/obj/project.nuget.cache
Unsupported file extension .cache for mime type text/plain for file /Users/redacted/Code/threatspec-demo/Threatdiagram Sample 1/obj/Debug/netcoreapp3.1/Threatdiagram Sample 1.csproj.CoreCompileInputs.cache
Unsupported file extension .cache for mime type text/plain for file /Users/redacted/Code/threatspec-demo/Threatdiagram Sample 1/obj/Debug/netcoreapp3.1/Threatdiagram Sample 1.genruntimeconfig.cache
Unsupported file extension .cache for mime type text/plain for file /Users/redacted/Code/threatspec-demo/Threatdiagram Sample 1/obj/Debug/netcoreapp3.1/Threatdiagram Sample 1.AssemblyInfoInputs.cache
Unsupported file extension .cs for mime type text/plain for file /Users/redacted/Code/threatspec-demo/Threatdiagram Sample 1/obj/Debug/netcoreapp3.1/Threatdiagram Sample 1.AssemblyInfo.cs
Unsupported file extension .cfg for mime type text/plain for file /Users/redacted/Code/threatspec-demo/venv/pyvenv.cfg
Unsupported file extension .fish for mime type text/plain for file /Users/redacted/Code/threatspec-demo/venv/bin/activate.fish
Unsupported file extension  for mime type text/plain for file /Users/redacted/Code/threatspec-demo/venv/bin/activate
Unsupported file extension .csh for mime type text/plain for file /Users/redacted/Code/threatspec-demo/venv/bin/activate.csh
Unsupported file extension .py for mime type text/plain for file /Users/redacted/Code/threatspec-demo/venv/lib/python3.7/site-packages/easy_install.py
Unsupported file extension .py for mime type text/plain for file /Users/redacted/Code/threatspec-demo/venv/lib/python3.7/site-packages/_pyrsistent_version.py
Unsupported file extension  for mime type text/plain for file /Users/redacted/Code/threatspec-demo/venv/lib/python3.7/site-packages/python_magic_bin-0.4.14.dist-info/RECORD
Unsupported file extension  for mime type text/plain for file /Users/redacted/Code/threatspec-demo/venv/lib/python3.7/site-packages/python_magic_bin-0.4.14.dist-info/WHEEL
Unsupported file extension .rst for mime type text/plain for file /Users/redacted/Code/threatspec-demo/venv/lib/python3.7/site-packages/python_magic_bin-0.4.14.dist-info/DESCRIPTION.rst
Unsupported file extension  for mime type text/plain for file /Users/redacted/Code/threatspec-demo/venv/lib/python3.7/site-packages/python_magic_bin-0.4.14.dist-info/INSTALLER
Unsupported file extension  for mime type text/plain for file /Users/redacted/Code/threatspec-demo/venv/lib/python3.7/site-packages/python_magic_bin-0.4.14.dist-info/METADATA
Traceback (most recent call last):
  File "/Users/redacted/Code/threatspec-demo/venv/bin/threatspec", line 11, in <module>
    load_entry_point('threatspec==0.5.0', 'console_scripts', 'threatspec')()
  File "/Users/redacted/Code/threatspec-demo/venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/redacted/Code/threatspec-demo/venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/redacted/Code/threatspec-demo/venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/redacted/Code/threatspec-demo/venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/redacted/Code/threatspec-demo/venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/redacted/Code/threatspec-demo/venv/lib/python3.7/site-packages/threatspec/cli.py", line 123, in run
    threatspec.run()
  File "/Users/redacted/Code/threatspec-demo/venv/lib/python3.7/site-packages/threatspec/app.py", line 232, in run
    self.parse_source(self.config.paths, data.cwd())
  File "/Users/redacted/Code/threatspec-demo/venv/lib/python3.7/site-packages/threatspec/app.py", line 88, in parse_source
    self.parser.parse_file(path)
  File "/Users/redacted/Code/threatspec-demo/venv/lib/python3.7/site-packages/threatspec/parser.py", line 165, in parse_file
    for comment in comment_parser.extract_comments(filename, self.mime):
  File "/Users/redacted/Code/threatspec-demo/venv/lib/python3.7/site-packages/comment_parser/comment_parser.py", line 79, in extract_comments
    return extract_comments_from_str(code.read(), mime)
  File "/Users/redacted/Code/threatspec-demo/venv/lib/python3.7/site-packages/comment_parser/comment_parser.py", line 106, in extract_comments_from_str
    return parser.extract_comments(code)
  File "/Users/redacted/Code/threatspec-demo/venv/lib/python3.7/site-packages/comment_parser/parsers/python_parser.py", line 24, in extract_comments
    for toknum, tokstring, tokloc, _, _ in tokens:
  File "/Users/redacted/.pyenv/versions/3.7.7/lib/python3.7/tokenize.py", line 572, in _tokenize
    ("<tokenize>", lnum, pos, line))
  File "<tokenize>", line 106
    pass
    ^
IndentationError: unindent does not match any outer indentation level
```

**Comment by schmitthub** [comment]
Fixed.

python-magic-bin was the issue. Installing libmagic with homebrew fixed it (`brew install libmagic`)

**Comment by schmitthub** [comment]
I think another fix could have been to exclude my virtual env dir (`./venv`)
