### ISSUE TITLE
Error: AttributeError: module 'magic' has no attribute 'from_file'

### ISSUE THREAD

**Issue by vdun** [threatspec/threatspec#41]
```
# threatspec run                                      
Running threatspec...
Traceback (most recent call last):
  File "/usr/bin/threatspec", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/threatspec/cli.py", line 123, in run
    threatspec.run()
  File "/usr/lib/python3.9/site-packages/threatspec/app.py", line 232, in run
    self.parse_source(self.config.paths, data.cwd())
  File "/usr/lib/python3.9/site-packages/threatspec/app.py", line 86, in parse_source
    self.parser = self.get_parser_for_path(path, config_path)
  File "/usr/lib/python3.9/site-packages/threatspec/app.py", line 37, in get_parser_for_path
    mime = magic.from_file(path, mime=True)
AttributeError: module 'magic' has no attribute 'from_file'
```

**Comment by zeroXten** [comment]
I'll see if I can replicate it.
